backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'feat(content): create {{collection}} “{{slug}}”'
    update: 'refactor(content): update {{collection}} “{{slug}}”'
    delete: 'refactor(content): delete {{collection}} “{{slug}}”'
    uploadMedia: 'feat(media): [skip ci] upload “{{path}}”'
    deleteMedia: 'refactor(media): [skip ci] delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "photo"
    label: "Photography"
    folder: "src/pages/photography"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "photography"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Image", name: "featuredimage", widget: image}
      - {label: "Images", name: images, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text, required: false}]}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
  - name: "illustrations"
    label: "Illustrations"
    folder: "src/pages/illustrations"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "illustrations"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Illustration", name: "featuredillustration", widget: image}
      - {label: "Illustrations", name: images, widget: list, fields: [{label: Illustration, name: image, widget: image}, {label: Text, name: text, widget: text, required: false}]}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
  - name: "case-studies"
    label: "Case Studies"
    folder: "src/pages/case-studies"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "case-studies"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Project Details", name: "project-details", widget: object, fields: [{label: Role, name: role, widget: text, required: false}, {label: Team, name: team, widget: text, required: false}, {label: Client, name: client, widget: text, required: false}]}
      - {label: "Featured Image", name: "featuredimage", widget: image}
      - {label: Body, name: body, widget: markdown}
      - {label: "Tags", name: "tags", widget: "list"}
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Subheading, name: subheading, widget: string}
          - {label: Mainpitch, name: mainpitch, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description, widget: text}]}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string, required:}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "Featured Image", name: "featuredimage", widget: image}
          - {label: "Images", name: images, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text, required: false}]}
          - {label: "Artist Statement Title", name: "artist-statement-title", widget: "string"}
          - {label: "Artist Statement", name: "artist-statement", widget: "text"}



